export enum ESettingsActionTypes {
  SET_SETTINGS_ITEM_REQUEST = "SETTINGS/SET_SETTINGS_ITEM_REQUEST",
  SET_SETTINGS_ITEM_SUCCESS = "SETTINGS/SET_SETTINGS_ITEM_SUCCESS",
  SET_SETTINGS_ITEM_FAILURE = "SETTINGS/SET_SETTINGS_ITEM_FAILURE",
}
