export enum ETasksActionTypes {
  ADD_TASK_REQUEST = 'TASKS/ADD_TASK_REQUEST',
  ADD_TASK_SUCCESS = 'TASKS/ADD_TASK_SUCCESS',
  ADD_TASK_FAILURE = 'TASKS/ADD_TASK_FAILURE',

  REMOVE_TASK_REQUEST = 'TASKS/REMOVE_TASK_REQUEST',
  REMOVE_TASK_SUCCESS = 'TASKS/REMOVE_TASK_SUCCESS',
  REMOVE_TASK_FAILURE = 'TASKS/REMOVE_TASK_FAILURE',

  GET_TASKS_REQUEST = 'TASKS/GET_TASKS_REQUEST',
  GET_TASKS_SUCCESS = 'TASKS/GET_TASKS_SUCCESS',
  GET_TASKS_FAILURE = 'TASKS/GET_TASKS_FAILURE',

  SET_CURRENT_TASK = 'TASKS/SET_CURRENT_TASK',
}
